# Generated by Django 5.1.7 on 2025-03-16 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wisdom_points', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_items', models.JSONField(default=dict)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_type', models.CharField(choices=[('RIDDLE', 'Linguistic Riddle'), ('LOGIC', 'Logic Trial'), ('FAITH', 'Faith-Based Puzzle'), ('DEBATE', 'Philosophical Debate')], max_length=20)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('hint', models.TextField(blank=True, null=True)),
                ('wisdom_points', models.IntegerField(default=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='main.room')),
            ],
        ),
    ]
